"""Generate assets/css/fonts.css from the shipped font binaries.

The fallback descriptors are measured from the WOFF2 files in assets/fonts/,
never copied from published figures, because a wrong override is invisible until
someone on a slow connection sees the page reflow.

The fallback side cannot be measured: Arial and Courier New are not in this
repo and are not ours to ship. Their metrics below are the published values for
the standard releases and are labelled as such.

Run:  python _tools/fonts.py          write assets/css/fonts.css
      python _tools/fonts.py --check  exit 1 if it is out of date
"""
import io
import os
import sys

try:
    from fontTools.ttLib import TTFont
except ImportError:
    sys.exit("fontTools is required:  pip install fonttools brotli")

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FONT_DIR = os.path.join(ROOT, "assets", "fonts")
OUT = os.path.join(ROOT, "assets", "css", "fonts.css")

# Published metrics for the fallback faces. Not measured here: these fonts are
# not in the repo. Units are font units over unitsPerEm.
FALLBACKS = {
    "arial": {
        "upm": 2048, "xHeight": 1062, "ascent": 1854, "descent": 434,
        "lineGap": 67, "advance": None,
        "stack": "local('Arial'), local('Helvetica Neue'), local('Roboto')",
    },
    "courier": {
        "upm": 2048, "xHeight": 866, "ascent": 1705, "descent": 615,
        "lineGap": 0, "advance": 1229,
        "stack": "local('Courier New'), local('Menlo'), local('DejaVu Sans Mono')",
    },
}

FACES = [
    ("IBM Plex Sans", "ibm-plex-sans-400.woff2", 400),
    ("IBM Plex Sans", "ibm-plex-sans-600.woff2", 600),
    ("IBM Plex Mono", "ibm-plex-mono-400.woff2", 400),
    ("IBM Plex Mono", "ibm-plex-mono-500.woff2", 500),
]

# family -> (fallback key, match on "x-height" or "advance")
MATCH = {
    "IBM Plex Sans": ("arial", "x-height"),
    "IBM Plex Mono": ("courier", "advance"),
}


def measure(path):
    font = TTFont(path)
    head, hhea, os2 = font["head"], font["hhea"], font["OS/2"]
    upm = head.unitsPerEm
    widths = font["hmtx"].metrics
    # A monospaced face has one advance for every glyph that has one.
    advances = [w for w, _lsb in widths.values() if w]
    common = max(set(advances), key=advances.count) if advances else 0
    return {
        "upm": upm,
        "xHeight": getattr(os2, "sxHeight", 0) or 0,
        "ascent": hhea.ascent,
        "descent": abs(hhea.descent),
        "lineGap": hhea.lineGap,
        "advance": common,
        "bytes": os.path.getsize(path),
    }


def build():
    lines = [
        "/* Generated by _tools/fonts.py. Do not hand-edit.",
        " *",
        " * IBM Plex Sans and IBM Plex Mono, SIL Open Font License 1.1.",
        " * Licence text ships beside the binaries at assets/fonts/OFL.txt.",
        " *",
        " * Two faces, one voice. Sans is what the site asserts; mono is what it",
        " * measured. Every figure on the site is mono, so a number always looks",
        " * like a reading rather than a claim.",
        " */",
        "",
    ]
    report = []

    for family, filename, weight in FACES:
        path = os.path.join(FONT_DIR, filename)
        if not os.path.isfile(path):
            sys.exit(f"missing font: {path}")
        m = measure(path)
        report.append((filename, weight, m))
        lines += [
            "@font-face {",
            f"  font-family: '{family}';",
            f"  src: url('../fonts/{filename}') format('woff2');",
            f"  font-weight: {weight};",
            "  font-style: normal;",
            "  font-display: swap;",
            "}",
            "",
        ]

    # One fallback face per family, sized so the swap is a nudge, not a jump.
    for family, (fb_key, mode) in MATCH.items():
        src = next(f for fam, f, _w in FACES if fam == family)
        m = measure(os.path.join(FONT_DIR, src))
        fb = FALLBACKS[fb_key]

        if mode == "x-height":
            web_ratio = m["xHeight"] / m["upm"]
            fb_ratio = fb["xHeight"] / fb["upm"]
            note = "matched on x-height"
        else:
            web_ratio = m["advance"] / m["upm"]
            fb_ratio = fb["advance"] / fb["upm"]
            note = ("matched on ADVANCE WIDTH, not x-height. Mono carries tabular\n"
                    "   *  figures in columns, and a column that changes width on font swap\n"
                    "   *  is worse than one that swaps at a slightly smaller optical size")

        size_adjust = web_ratio / fb_ratio
        # The overrides are percentages of the ADJUSTED em, so divide through.
        ascent = (m["ascent"] / m["upm"]) / size_adjust
        descent = (m["descent"] / m["upm"]) / size_adjust
        line_gap = (m["lineGap"] / m["upm"]) / size_adjust

        lines += [
            f"/* {family} fallback, {note}. */",
            "@font-face {",
            f"  font-family: '{family} Fallback';",
            f"  src: {fb['stack']};",
            f"  size-adjust: {size_adjust * 100:.3f}%;",
            f"  ascent-override: {ascent * 100:.3f}%;",
            f"  descent-override: {descent * 100:.3f}%;",
            f"  line-gap-override: {line_gap * 100:.3f}%;",
            "}",
            "",
        ]

    return "\n".join(lines), report


def main():
    css, report = build()
    check = "--check" in sys.argv

    total = sum(m["bytes"] for _f, _w, m in report)
    print("measured from the shipped binaries:")
    for filename, weight, m in report:
        print(f"  {filename:26} w{weight}  upm {m['upm']}  xh {m['xHeight']}  "
              f"asc {m['ascent']}  desc {m['descent']}  adv {m['advance']}  "
              f"{m['bytes'] / 1024:.1f} KB")
    print(f"  {'':26} {total / 1024:.0f} KB total for four faces")

    current = io.open(OUT, encoding="utf-8").read() if os.path.isfile(OUT) else None
    if current == css:
        print("\nfonts.css is current")
        return 0
    if check:
        print("\nfonts.css is OUT OF DATE; run python _tools/fonts.py")
        return 1

    io.open(OUT, "w", encoding="utf-8", newline="\n").write(css)
    print(f"\nwrote {os.path.relpath(OUT, ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
